### PR TITLE
bytes: require 0.4.4

### PR DESCRIPTION
**Pull request by mathstuf**
Various APIs used in this crate were added in 0.4.4.

### CODE REVIEW

**Comment by mathstuf** [comment]
Hrm. Seems `bytes` itself needs some work for minimal-versions in some cases. I'll have a followup within a few days.

**Comment by mathstuf** [comment]
Requires a release of https://github.com/tokio-rs/bytes/pull/312

**Comment by mathstuf** [comment]
I poked the bottom of this PR hole; hopefully it can cause some movement to let this get merged :) .

**Comment by carllerche** [comment]
looks like a conflict ::(

**Comment by mathstuf** [comment]
Not surprising; I'll rebase once the dependent PRs are merged (and have a release on crates.io to depend on).

**Comment by dekellum** [comment]
Conflict with #364 and specifically 845fdd1?

**Comment by mathstuf** [comment]
Well, this might need to go to 0.1.x as well now because of that :) .

**Comment by dekellum** [comment]
Branch whack-a-mole!   Seriously, thanks for trying to fix this. I hope there is a potential for an 0.1.21 with the fix, as I suspect some projects will need to support both http 0.1 and 0.2 for some transition period.

**Comment by mathstuf** [comment]
I'll probably be back for 0.2 at some point. I've got a lot of plates in the air for my own set of crates at the moment before I can start to *actually* fix everything :) .

**Comment by mathstuf** [comment]
Ping?

**Comment by LucioFranco** [comment]
@mathstuf is this something we still want to go with or should we close this in favor of ensuring 0.5 has all the fixes we need?

**Comment by mathstuf** [comment]
Oh, my bad. I thought this was the bottom of my stack. This will need the PR mentioned above first. Sorry for the noise. Going down one level deeper.

**Comment by kaj** [comment]
If there is action on #440 this should probably just be closed as semi-duplicate.

**Comment by mathstuf** [comment]
I'm more interested in `minimum-versions` support, so if that fixes it, I'm fine with that.

**Comment by robjtede** [comment]
this can be closed

**Comment by mathstuf** [comment]
It looks like #440 also got closed. Would another minimal versions support PR make it any further?

**Comment by seanmonstar** [comment]
Yea, it'd be a good thing to add to CI. Sorry we missed these, but we have more attention now.

**Pull request closed without merging**
