### PR TITLE
added shortcut methods to create request builder with method and uri

### PR DESCRIPTION
**Pull request by krampenschiesser**
I am using the http library in my project and I was missing shortcut methods to create requests in a simple manner.

### CODE REVIEW

**Comment by carllerche** [comment]
The idea is good, I wonder if these fns should return requests directly instead of builders.

Also, we know that POST and PUT requests will have bodies, so should the body be accepted as an argument?

**Comment by krampenschiesser** [comment]
I would prefer builders, in order to add occasional headers or, as you said, a body.

**Comment by seanmonstar** [comment]
> Also, we know that POST and PUT requests will have bodies, so should the body be accepted as an argument?

POST may have a body, but lots of POST endpoints with an empty body also exist. It is pretty weird to have PUT without a body... but it's also super easy to add a body after.

**Comment by carllerche** [comment]
I'll allow it.

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
