### PR TITLE
deps: update ordermap to 0.4

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by carllerche** [comment]
I believe that this is now [indexmap](https://crates.io/crates/indexmap). Would you mind switching to that instead?

Thanks for the work!

**Comment by ignatenkobrain** [comment]
Yeah, time flies. I will update to indexmap.

**Comment by ignatenkobrain** [comment]
pushed, let's see.

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
