### PR TITLE
Return error if multiple brackets exist in the authority

### LINKED ISSUE #435: Unexpected panic for malformed URI with brackets
Doing some fuzzing I encountered this:

```
    let uri = "http://[]@[";
    let uri = uri.parse::<http::Uri>().unwrap(); // is ok
    uri.host(); // panics
```

The panic is `parsing should validate brackets` and come from here: https://github.com/hyperium/http/blob/v0.2.1/src/uri/authority.rs#L486

I expect this to surface as an `Err` and panic on `.unwrap()`.

### PR DESCRIPTION
**Pull request by aeryz**
Fixes #435

### CODE REVIEW

**Review by seanmonstar — COMMENTED** [review]
This looks good to me, it'd be good to add the unit tests the value that was triggering the panic.

**Comment by aeryz** [comment]
I added a test which tests the exact string that causes the bug.

**Review by seanmonstar — APPROVED** [review]
Thanks!

**Comment by algesten** [comment]
Thanks!

**Pull request merged**
