### PR TITLE
Enable simpler header name parser in debug builds

### PR DESCRIPTION
**Pull request by ibraheemdev**
This shaves close to a second off debug builds on my machine.

### CODE REVIEW

**Comment by hawkw** [comment]
If we're going to do this, it seems like it might also be a good idea to add a CI step to run the tests in release mode? Otherwsie, most of the parser code is no longer tested on CI.

**Comment by seanmonstar** [comment]
Maybe I'm misunderstanding... Seems this is turning off the debug assertions?

**Comment by ibraheemdev** [comment]
It makes it so the simpler version of `parse_hdr` in any debug builds, instead of only in WASM debug builds. `debug_assertions` is the cfg flag that identifies a debug build (ish).

**Comment by seanmonstar** [comment]
I'd normally think in a debug build we'd want the  extra checks.

**Comment by jeddenlea** [comment]
https://github.com/hyperium/http/pull/499 removes the `eq` macro in all cases.

**Comment by ibraheemdev** [comment]
Closing in favor of #499.

**Pull request closed without merging**
